### ISSUE TITLE
TypeError: response.buffer is not a function

### ISSUE THREAD

**Issue by p0ryae** [dragonfire535/node-superfetch#122]
**Please describe the problem you are having in as much detail as possible**:
TypeError: response.buffer is not a function. This is likely a node-related issue. Please add support.

The alternative to .buffer() is now .arrayBuffer()

**Further details**:

- node-superfetch version: 3.0.0
- Node.js version: v18.10.0
- Operating system: Arch Linux

**Comment by xiaobotdev** [comment]
Fixed in latest version. Do note that body will return a buffer, not an arraybuffer.
