### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by overtimepog** [dragonfire535/node-superfetch#34]
**Please describe the problem you are having in as much detail as possible**:
How do I use headers with this (an example would be nice)

**Further details**:

- node-superfetch version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by xiaobotdev** [comment]
You can add headers with the `set` function.
```js
request.get('url').set({ header: 'value' })
// or
request.get('url').set('header', 'value')
```
